#!/usr/bin/env bash
# Install Nginx on web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod a+w /var/www/html/index.nginx-debian.html
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start

