#!/usr/bin/env bash
# Script that configure Nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo chmod a+w /var/www/html/index.nginx-debian.html
echo "Hello World" > /var/www/html/index.nginx-debian.html
cat /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i "/http {/ a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
