#!/usr/bin/env bash
# Script that download a Haproxy and a configures the load balancer

sudo apt-get update
sudo apt-get -y install haproxy

# Configuration load balancer
# frontend part
echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend myservers\n\n"| sudo tee -a /etc/haproxy/haproxy.cfg

# Backend part
echo -e "backend myservers\n\tbalance roundrobin\n\tserver web-01 34.139.21.162:80 check\n\tserver web-02 34.207.116.166:80 check"| sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
