#!/usr/bin/env bash
#script that displays numbers from 1 to 100.

#i=0
for i in {1..100};
do
    if [ $((i % 3)) -eq 0 ];
    then
	echo "Fizz"
    elif [ $((i % 5)) -eq 0 ];
    then
	echo "Buzz"
    elif [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ];
    then
	echo "FizzBuzz"
    else
	echo "$i"
    fi
done
