#!/usr/bin/env bash
#Script that print using if elif and else conditionals
var='Best School'

i=1
while [ $i -le 10 ];
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "good luck"
	else
		echo "$var"

	fi
	((i++))
done
