#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
sudo cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
sed -i "2i/facebook.com/8.8.8.8/" ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
